name: lister
description: To-do list in your phone.
publish_to: 'meg4cyberc4t'

version: 1.3.0+7

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.0.4
  hive_flutter: ^1.0.0
  # pie_chart: ^5.0.0
  # url_launcher: ^6.0.6
  flutter_launcher_icons: ^0.9.0
  # package_info: ^2.0.2
  google_nav_bar: ^5.0.5
  # day_night_time_picker: ^1.0.2
  intl: ^0.17.0
  flutter_bloc: ^7.0.1
  equatable: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.0
  build_runner: ^1.8.1


flutter:
  uses-material-design: true
  assets:
  - assets/moon.png
  - assets/sun.png

  fonts:
    - family: Montserrat
      fonts:
      - asset: fonts/Montserrat-Regular.ttf

  

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "icon.png"