name: lister
description: To-do list in your phone.
publish_to: 'cybercat'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.0.4
  flutter_slidable: ^0.6.0
  persistent_bottom_nav_bar: ^4.0.2
  hive_flutter: ^1.0.0
  pie_chart: ^5.0.0
  url_launcher: ^6.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.0
  build_runner: ^1.8.1


flutter:
  uses-material-design: true
  fonts:
    - family: Montserrat
      fonts:
      - asset: fonts/Montserrat-Regular.ttf

